(("runemacs" . ((user-emacs-directory . "~/runemacs-emacs.d")))
 ("spacemacs" . ((user-emacs-directory . "~/spacemacs-emacs.d")))
 ("doom" . ((user-emacs-directory . "~/doom-emacs.d")
           (env . (("DOOMDIR" . "~/.doom.d")))))
)
